export const CONNECTION_GAMES = [
  // [
  //   {
  //     category: "1960s",
  //     words: ["KENNEDY IS KILLED BY SNIPER AS HE RIDES IN CAR...", "MEN WALK ON MOON", "FURTHER UPHEAVAL IN CHINA FORESEEN IN POWER BATTLE...", "EAST GERMAN TROOPS SEAL BORDER WITH WEST BERLIN TO BLOCK REFUGEE ESCAPE"],
  //     difficulty: 2,
  //   },
  //   {
  //     category: "2000s",
  //     words: ["BUSH APPEARS TO DEFEAT GORE", "IN SWEEPING MOVE, FED BACKS BUYOUT AND WALL ST. LOANS", "2 ENRON CHIEFS ARE CONVICTED IN FRAUD AND CONSPIRACY TRIAL", "BUSH DECLARES 'ONE VICTORY IN A WAR ON TERROR'"],
  //     difficulty: 1,
  //   },
  //   {
  //     category: "1930s",
  //     words: ["NINTH PLANET DISCOVERED ON EDGE OF SOLAR SYSTEM; ...", "GANDHI SEIZED BY BRITISH FOR INDEFINITE...", "BOTH HOUSES OVERWHELM PRESIDENT'S VETO OF BILL ON SPANISH WAR PENSIONS", "U.S. CONDEMNS JAPAN AS INVADER OF CHINA; DROPS NEUTRALITY POLICY..."],
  //     difficulty: 3,
  //   },
  //   {
  //     category: "1910s",
  //     words: ["TITANIC SINKS FOUR HOURS AFTER HITTING ICEBERG", "HEIR TO AUSTRIA'S THRONE IS SLAIN WITH HIS WIFE BY A BOSNIAN YOUTH...", "EDWARD VII. DIES OF PNEUMONIA; GEORGE V. REIGNS OVER ENGLAND", "TWO HELD FOR BIG STOCK STAMP STEAL"],
  //     difficulty: 4,
  //   },
  // ],
  // [
  //   {
  //     category: "1980s",
  //     words: ["THE SHUTTLE EXPLODES - 6 IN CREW AND HIGH SCHOOL...", "REAGAN EASILY BEATS CARTER; REPUBLICANS GAIN IN CONGRESS", "SOVIET, REPORTING ATOM PLANT 'DISASTER,' SEEKS HELP..", "JOHN LENNON OF BEATLES IS KILLED; SUSPECT HELD..."],
  //     difficulty: 3,
  //   },
  //   {
  //     category: "1990s",
  //     words: ["DIANA KILLED IN A CAR ACCIDENT IN PARIS", "GORBACHEV, LAST SOVIET LEADER, RESIGNS", "CLINTON ADMITS LEWINSKY LIAISON TO JURY", "THATCHER SAYS SHE'LL QUIT; 11 1/2 YEARS AS PRIME..."],
  //     difficulty: 2,
  //   },
  //   {
  //     category: "1940s",
  //     words: ["JAPAN WARS ON U.S. AND BRITAIN; MAKES SUDDEN ATTACK...", "THE WAR IN EUROPE IS ENDED! SURRENDER ...", "TROTSKY DIES OF HIS WOUNDS; ASKS REVOLUTION ....", "INDIA AND PAKISTAN BECOME NATIONS; CLASHES CONTINUE"],
  //     difficulty: 4,
  //   },
  //   {
  //     category: "2020s",
  //     words: ["U.S. DEATHS NEAR 100,000, AN INCALCULABLE LOSS", "TRUMP INCITES MOB", "ROE OVERTURNED", "TALIBAN CAPTURE KABUL, STUNNING U.S. AS A 20-YEAR EFFORT.."],
  //     difficulty: 1,
  //   },
  // ]
  [
    {
      category: "2010s",
      words: ["JUSTICE DEPT. AGREES TO TURN OVER KEY MUELLER EVIDENCE…", 
              "NETANYAHU SOUNDLY DEFEATS CHIEF RIVAL", 
              "A FREED BUT SCARRED CITY TESTS TRUMP...", 
              "GUNMAN MASSACRES 20 CHILDREN AT SCHOOL IN CONNECTICUT"],
      difficulty: 1,
    },
    {
      category: "1980s",
      words: ["TROOPS ATTACK AND CRUSH BEIJING PROTEST; THOUSANDS FIGHT BACK...", 
              "AMERICAN RELEASED BY IRANIANS ARRIVES IN SWITZERLAND",
              "INDIRA GANDHI ASSASSINATED BY GUNMEN...", 
              "U.S. IS CONSIDERING MUCH WIDER TESTS FOR AIDS INFECTION"
            ],
      difficulty: 2,
    },
    {
      category: "1950s",
      words: ["U.S. WILL GIVE MILITARY AID TO FRANCE AND INDO-CHINA IN DEFENSE AGAINST THE REDS", 
              "STALIN DIES AFTER 29-YEAR RULE, HIS SUCCESSOR NOT ANNOUNCED…", 
              "SALK POLIO VACCINE PROVES SUCCESS; MILLIONS WILL BE IMMUNIZED SOON...", 
              "DR. ALBERT EINSTEIN DIES IN SLEEP AT 76; WORLD MOURNS LOSS…"],
      difficulty: 3,
    },
    {
      category: "1930s",
      words: ["MANCHURIA ACTION BY LEAGUE NOV.14; JAPAN MAY RESIGN",
              "’ETHIOPIA IS ITALIAN,’ SAYS MUSSOLINI AS HIS TROOPS OCCUPY ADDIS ABABA…",
              "COMMUNISTS PLOT TO USE ROOSEVELT IN AIMS, FREY SAYS",
              "REICH TO SEEK LARGE LOAN, PARLEY IN LONDON JULY 17…"],
      difficulty: 4,
    }
  ]
];

