export const CONNECTION_GAMES = [
  [
    {
      category: "1960s",
      words: ["KENNEDY IS KILLED BY SNIPER AS HE RIDES IN CAR...", "MEN WALK ON MOON", "FURTHER UPHEAVAL IN CHINA FORESEEN IN POWER BATTLE...", "EAST GERMAN TROOPS SEAL BORDER WITH WEST BERLIN TO BLOCK REFUGEE ESCAPE"],
      difficulty: 2,
    },
    {
      category: "2000s",
      words: ["BUSH APPEARS TO DEFEAT GORE", "IN SWEEPING MOVE, FED BACKS BUYOUT AND WALL ST. LOANS", "2 ENRON CHIEFS ARE CONVICTED IN FRAUD AND CONSPIRACY TRIAL", "BUSH DECLARES 'ONE VICTORY IN A WAR ON TERROR'"],
      difficulty: 1,
    },
    {
      category: "1930s",
      words: ["NINTH PLANET DISCOVERED ON EDGE OF SOLAR SYSTEM; ...", "GANDHI SEIZED BY BRITISH FOR INDEFINITE...", "BOTH HOUSES OVERWHELM PRESIDENT'S VETO OF BILL ON SPANISH WAR PENSIONS", "U.S. CONDEMNS JAPAN AS INVADER OF CHINA; DROPS NEUTRALITY POLICY..."],
      difficulty: 3,
    },
    {
      category: "1910s",
      words: ["TITANIC SINKS FOUR HOURS AFTER HITTING ICEBERG", "HEIR TO AUSTRIA'S THRONE IS SLAIN WITH HIS WIFE BY A BOSNIAN YOUTH...", "EDWARD VII. DIES OF PNEUMONIA; GEORGE V. REIGNS OVER ENGLAND", "TWO HELD FOR BIG STOCK STAMP STEAL"],
      difficulty: 4,
    },
  ]
];
